language: objective-c

env:
  matrix:
    - MONO_VERSION=3.2.7
	- FSHARP_VERSION=3.1.1.1

install:
  - wget "http://download.xamarin.com/MonoFrameworkMDK/Macx86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
  - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /
  - wget "https://github.com/fsharp/fsharp/archive/${FSHARP_VERSION}.tar.gz" -O /tmp/fsharp-${FSHARP_VERSION}.tar.gz
  - (cd /tmp; tar xf fsharp-${FSHARP_VERSION}.tar.gz) && pushd /tmp/fsharp-${FSHARP_VERSION}
  - ./autogen.sh --prefix=/Library/Frameworks/Mono.framework/Versions/${MONO_VERSION}
  - make
  - sudo make install
  - popd

before_script:
 - chmod +x build.sh

script: 
  - ./build.sh All
